workload = {
    1: {  # fc
    "operator_type": "Conv",
    "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
    "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
    "loop_dim_size": {
        "B": 3,
        "K": 3,
        "C": 3,
        "OY": 1,
        "OX": 1,
        "FY": 1,
        "FX": 1,
    },
    "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
    "operand_source": {"W": [], "I": []},
    "constant_operands": ["W", "I"],
    },
    2: {  # fc
    "operator_type": "Conv",
    "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
    "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
    "loop_dim_size": {
        "B": 15,
        "K": 15,
        "C": 15,
        "OY": 1,
        "OX": 1,
        "FY": 1,
        "FX": 1,
    },
    "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
    "operand_source": {"W": [], "I": []},
    "constant_operands": ["W", "I"],
    },
    3: {  # fc
    "operator_type": "Conv",
    "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
    "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
    "loop_dim_size": {
        "B": 36,
        "K": 36,
        "C": 36,
        "OY": 1,
        "OX": 1,
        "FY": 1,
        "FX": 1,
    },
    "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
    "operand_source": {"W": [], "I": []},
    "constant_operands": ["W", "I"],
    },
    4: {  # fc
    "operator_type": "Conv",
    "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
    "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
    "loop_dim_size": {
        "B": 144,
        "K": 3,
        "C": 9,
        "OY": 1,
        "OX": 1,
        "FY": 1,
        "FX": 1,
    },
    "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
    "operand_source": {"W": [], "I": []},
    "constant_operands": ["W", "I"],
    },
    5: {  # fc
    "operator_type": "Conv",
    "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
    "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
    "loop_dim_size": {
        "B": 57,
        "K": 24,
        "C": 81,
        "OY": 1,
        "OX": 1,
        "FY": 1,
        "FX": 1,
    },
    "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
    "operand_source": {"W": [], "I": []},
    "constant_operands": ["W", "I"],
    },
    6: {  # fc
    "operator_type": "Conv",
    "equation": "O[b][k][oy][ox]+=W[k][c][fy][fx]*I[b][c][iy][ix]",
    "dimension_relations": ["ix=1*ox+1*fx", "iy=1*oy+1*fy"],
    "loop_dim_size": {
        "B": 9,
        "K": 9,
        "C": 9,
        "OY": 1,
        "OX": 1,
        "FY": 1,
        "FX": 1,
    },
    "operand_precision": {"O": 16, "O_final": 8, "W": 8, "I": 8},
    "operand_source": {"W": [], "I": []},
    "constant_operands": ["W", "I"],
    }
}